# Generated by Django 4.0.2 on 2022-05-29 10:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('basetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basetimemodel')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('number_of_likes', models.IntegerField(default=0)),
                ('number_of_shares', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
            bases=('core.basetimemodel',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('basetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basetimemodel')),
                ('content', models.TextField()),
                ('number_of_likes', models.IntegerField(default=0)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('commented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(to='articles.Comment')),
            ],
            bases=('core.basetimemodel',),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='articles.Tag'),
        ),
    ]
