# Generated by Django 4.0.2 on 2022-06-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_content_alter_article_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='is_subcomment_of', to='articles.Comment'),
        ),
    ]
