# Generated by Django 4.0.2 on 2022-06-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_comment_edited_comment_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='edited',
            new_name='is_edited',
        ),
    ]
